### ISSUE TITLE
Unsupported ROM/ Kernel

### ISSUE THREAD

**Issue by Nishasanthosh** [OTAUpdateCenter/ota-updater-2.0#37]
Hello,
      My mobile is huawei ascend G750, I purchased  the handset last year since then I am not yet received any updates.Now when I tried to update it from your site, it says Unsupported ROM/Kernel, the feature XML file is missing from my ROM/Kernel.Without this file I will not be able to update my device.Kindly do the needful to update my device.
Thank you

**Comment by mohmed1500** [comment]
#37

**Comment by lmourin** [comment]
Hi guy's
I have a Samsung Galaxy S3 and I'm exactly in this case described by Nishasanthosh.
Hope you'r apk can Soon support this phone.
So, let me know a good news... THANKS a lot

**Comment by ghost** [comment]
Having d same ish

**Comment by surain69** [comment]
Hello,
My mobile is Samsung galaxy grand neo i9060, I purchased the handset last year since then I am not yet received any updates.Now when I tried to update it from your site, it says Unsupported ROM/Kernel, the feature XML file is missing from my ROM/Kernel.Without this file I will not be able to update my device.Kindly do the needful to update my device.
Thank you
